# Generated by Django 4.2.16 on 2024-09-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sexo',
            table='Sexo',
        ),
    ]
